apiVersion: v1
kind: Namespace
metadata:
  name: fgc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiapcloudgames-users-api
  namespace: fgc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiapcloudgames-users-api
  template:
    metadata:
      labels:
        app: fiapcloudgames-users-api
    spec:
      containers:
      - name: users-api
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value:  "service.name=fgc,service.namespace=fgc,deployment.environment=Production" 
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://otlp-gateway-prod-sa-east-1.grafana.net/otlp"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "Authorization=Basic MTUwNDM5NDpnbGNfZXlKdklqb2lNVFkwT1RNMk9DSXNJbTRpT2lKbVoyTWlMQ0pySWpvaU1qUXdiVEJGTUZwUFFXZDJPVTltTTJkMVRtVXdOVWMwSWl3aWJTSTZleUp5SWpvaWNISnZaQzF6WVMxbFlYTjBMVEVpZlgwPQ=="
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"  
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: fiapcloudgames-users-api
  namespace: fgc
spec:
  type: ClusterIP
  selector:
    app: fiapcloudgames-users-api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
